---
packages:
  - "infra/*"
  - "mocks"
  - "federation/**"
  - "package/*"
  - "shared/*"
  - "shell/*"
  - "ui/*"

catalogs:
  node:
    "@types/node": ^22.7.9
  biome:
    "@biomejs/biome": 1.9.4
  tailwindcss:
    tailwindcss: ^3.4.14
    postcss: ^8.4.47
    autoprefixer: ^10.4.20
  react:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
  vite:
    vite: ^6.3.0
    "@vitejs/plugin-react": ^4.4.0
    "@module-federation/vite": ^1.2.6
    "@module-federation/runtime": ^0.12.0
    vite-tsconfig-paths: "^5.0.1"
    "yaml": "^2.6.0"
  vitest:
    vitest: ^2.1.9
catalog:
  typescript: ^5.8.3
  tsx: 4.19.2
  zod: ^3.24.2
